### ISSUE TITLE
aws not recognized

### ISSUE THREAD

**Issue by rainabba** [iandotkelly/aws-cli#1]
I've installed a number of global packages so I have no doubt that my paths are setup, but installed this and `aws` isn't recognized. Are there other dependencies?

**Comment by iandotkelly** [comment]
Hi.  It used to work, but as it says in the README, this is at a very basic implementation.

I will have a look at this for you if you can confirm one thing.  Do you want to use the 1 command that is supported iam-servercertdel - deleting a certificate ?

**Comment by rainabba** [comment]
At this time I'm not needing that command. No pressure about the issue either. I was just looking for a way to get the CLI via NPM (easier when it works), but I ended up installing the proper CLI from AWS. Since this is a know issue, feel free to close this issue.
